title: c3-tmp-r-sympathetic-8-ball
hero_image: images/banner.png
description: c3-tmp-r-sympathetic-8-ball description
version: 4
listed: false
copyedit: false
last_tested: "2019-03-18"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
